### PR TITLE
Notebook to build SFR in MongoDB

### PR DESCRIPTION
**Pull request by skybristol**
This notebook introduces some new functions and processing logic to
work source tables from GC2 into a new “synthesized” data structure
based on schema.org Place

### CODE REVIEW

**Comment by dwief-usgs** [comment]
@skybristol in your notebook "SFR attribute processing" you have a number of situations where you reference code similar to this.   "data.pop(idType, None)"

I wasn't familiar with this and after poking around found that it drops information from the json, but I couldn't figure out the significance of passing "None" .  I tested both   data.pop(idType, None) and "data.pop(idType) and got the same results.  The only documentation I found says to pass the index and that is all.

**Comment by dwief-usgs** [comment]
@skybristol was the function lookupState included in the notebook "SFR attribute processing" as an option for adding abbreviations to the state data?  I think we should drop it or add some explanation to the notebook.

**Comment by skybristol** [comment]
Adding none handles cases where the key you are popping doesn’t exist. Yep. We can remove lookupState. I decided to move that to a secondary function somewhere.

**Comment by dwief-usgs** [comment]
another suggestion for this notebook is adding some sort of indicator of type of geometry.  I've looked at the place schema.org but haven't found a definitive way of denoting this within the schema.  Maybe we can add it in as an additionalProperty

@type : PropertyValue
propertyID : GeoShape
value :  point, line, polygon, multipoint, multiline, or multipolygon

I also looked at the geo -> GeoShape part of the schema but without specifically recording the geometry I didn't find any place to house the information, unless we did an additional type within GeoShape?

thought?

**Pull request merged**
